/**
 * Represents an encrypted message stored in the relay.
 * The payload is opaque to the relay — all encryption/decryption happens client-side.
 */
export interface Message {
  /** UUID, auto-generated by the relay server */
  id: string;
  /** Recipient wallet address */
  to: string;
  /** Sender wallet address */
  from: string;
  /** Encrypted data (base64 string, opaque to server) */
  payload: string;
  /** ISO 8601 timestamp when message was stored */
  createdAt: string;
  /** ISO 8601 timestamp when message will be auto-purged, or null if stored forever */
  expiresAt: string | null;
}

/**
 * Parameters for sending a message via the relay.
 */
export interface SendParams {
  /** Recipient wallet address */
  to: string;
  /** Sender wallet address */
  from: string;
  /** Encrypted payload (base64 string) */
  payload: string;
}

/**
 * Configuration options for the RelayClient.
 */
export interface ClientOptions {
  /** API key for authenticated relay servers. Sent as X-API-Key header. */
  apiKey?: string;
  /** Request timeout in milliseconds. Default: 10000 (10 seconds) */
  timeout?: number;
  /** Number of retry attempts on network errors / 5xx responses. Default: 3 */
  retries?: number;
}

/**
 * Options for the poll() method.
 */
export interface PollOptions {
  /** Polling interval in milliseconds. Default: 10000 (10 seconds) */
  intervalMs?: number;
  /** Optional callback for handling polling or network errors */
  onError?: (error: Error) => void;
}

/**
 * Health check response from the relay server.
 */
export interface HealthResponse {
  status: string;
  timestamp: string;
}
